#!/bin/bash

LABYRDIR="$HOME/.labyrinth/"
LABYRTERM="alacritty -e nvim -c terminal"
LABYRMU="alacritty -e ncmpcpp"
LABYRTERM2='alacritty'
MUREMOTE="mpc"
MUDL="yt-dlp --embed-metadata -x --audio-format opus --audio-quality 0 -o '~/Music/collection/rnd/%(title)s.%(ext)s' $(xsel -b)"
LABYREDIT="$LABYRTERM2 -e nvim"
LABYRGAL='nomacs'
LABYRDAW='reaper'
LABYRDAW2='bitwig-studio'
LABYRWEB='qutebrowser'
LABYRWAL='nitrogen'
LABYRMODE=$(cat ~/.config/sxhkd/current_mode)

case "$1" in

    -g) 
        exec $LABYRGAL $2 &
        ;;

    -m)
        exec $LABYRMU $2 & 
        ;;

    -mr) 

        exec $MUREMOTE $2 &
        ;;

    -dv)
        exec $LABYRTERM2 $MUDL &
        ;;

    -e)
        exec $LABYREDIT $2 &
        ;;

    -E)

        exec $LABYRTERM2 -e $2 &
        ;;

    -t)
        exec $LABYRTERM $2 &
        ;;

    -w)
        exec $LABYRWAL $2 &
        ;;

    -b)
        exec $LABYRWEB $2 &
        ;;

    -M)
        notify-send $LABYRMODE
        ;;

    -sf)
        selection=$(hacksaw -f "-i %i -g %g" -f fullscreen)
        shotgun $selection - | xclip -selection clipboard -t image/png
        
        option=$(echo -e "Yes\nNo" | dmenu -i -p "::save")
        if echo "$option" | grep -q "Yes"; then
            filename=$(echo | dmenu -p "Enter filename:") && \
            filename=${filename:-$(date +%s)} && \
            mkdir -p ~/Pictures/Screenshots
            
            shotgun $selection ~/Pictures/Screenshots/"$filename.png"
        fi

        ;;


    -ss)
        selection=$(hacksaw -f "-i %i -g %g")
        
        shotgun $selection - | xclip -selection clipboard -t image/png
        
        option=$(echo -e "Yes\nNo" | dmenu -i -p "::save")
        
        if echo "$option" | grep -q "Yes"; then
            filename=$(echo | dmenu -p "Enter filename:") && \
            filename=${filename:-$(date +%s)} && \
            mkdir -p ~/Pictures/Screenshots
            
            shotgun $selection ~/Pictures/Screenshots/"$filename.png"
        fi
        ;;

esac 
