#!/bin/bash


LABYRDIR="$HOME/.labyrinth/"
LABYRTERM="alacritty"
LABYRMU="alacritty -e cmus"
LABYRMPC="vimpc"
LABYRTERM2='xterm'
MUREMOTE="mpc"
MUDL="yt-dlp --embed-metadata -x --audio-format opus --audio-quality 0 -o '~/Music/collection/rnd/%(title)s.%(ext)s' $(xsel -b)"
LABYREDIT="$LABYRTERM2 -e vim"
LABYRGAL='nomacs'
LABYRDAW='reaper'
LABYRDAW2='bitwig-studio'
LABYRWEB='qutebrowser'
LABYRWAL='nitrogen'
LABYRMODE=$(cat ~/.config/sxhkd/current_mode)
LABYRFM="vifm"
WIDIR="$HOME/.widow"
MUCOL="$HOME/Music/collection/rnd/"

case "$1" in

    -g) 
        exec $LABYRGAL $2 &
        ;;

    -m)
        exec $LABYRMU $2 & 
        ;;

    -mr) 

        exec $MUREMOTE $2 &
        ;;

    -dv)
        exec $LABYRTERM2 $MUDL &
        ;;

    -e)
        exec $LABYREDIT $2 &
        ;;

    -E)

        exec $LABYRTERM2 -e $2 &
        ;;

    -t)
        exec $LABYRTERM $2 &
        ;;

    -w)
        exec $LABYRWAL $2 &
        ;;

    -b)
        exec $LABYRWEB $2 &
        ;;

    -M)
        notify-send $LABYRMODE
        ;;

    -sf)
	
        shotgun - | xclip -selection clipboard -t image/png
        
        option=$(echo -e "Yes\nNo" | dmenu -i -p "::save")
        if echo "$option" | grep -q "Yes"; then
            filename=$(echo | dmenu -p "Enter filename:") && \
            filename=${filename:-$(date +%s)} && \
            mkdir -p $WIDIR/.rec/img
            
            shotgun $WIDIR/.rec/img/"$filename.png"
        fi

        ;;


    -ss)
        selection=$(hacksaw -f "-i %i -g %g")
        
        shotgun $selection - | xclip -selection clipboard -t image/png
        
        option=$(echo -e "Yes\nNo" | dmenu -i -p "::save")
        
        if echo "$option" | grep -q "Yes"; then
            filename=$(echo | dmenu -p "Enter filename:") && \
            filename=${filename:-$(date +%s)} && \
            mkdir -p $WIDIR/.rec/img
            
            shotgun $selection $WIDIR/.rec/img/"$filename.png"
        fi
        ;;

   -sv)

    	dir=$WIDIR/.rec/vi
    	current=$(date +%F_%H-%M-%S)
    	
    	mkdir -p "$dir"
    	
    	hacksaw | {
    	    IFS=+x read -r w h x y
    	
    	    w=$((w + w % 2))
    	    h=$((h + h % 2))
    	
    	    $LABYRTERM -e ffmpeg \
    	        -v 16            \
    	        -r 30            \
    	        -f x11grab       \
                -s "${w}x${h}"   \
    	        -i ":0.0+$x,$y"  \
    	        -preset slow     \
    	        -c:v h264        \
    	        -pix_fmt yuv420p \
    	        -crf 20          \
    	        "$dir/$current.mp4" 
    		}
	;;

   -ar)

   	   directory=$WIDIR/.rec/au
   	   date=$(date +%F_%H-%M-%S)
           $LABYRTERM -e ffmpeg -f alsa -i default "$directory/$date".wav

    	;;
   
   -ad)

          $LABYRTERM -e yt-dlp -x --audio-format m4a --postprocessor-args "-b 320k" --audio-quality 0 --prefer-ffmpeg --add-metadata "$(xsel -b)" --embed-thumbnail -o "$MUCOL/%(title)s.%(ext)s"
	;; 

   -fm)
       $LABYRFM $1
       ;;
esac 
